CREATE DATABASE LECTI;
USE LECTI;

CREATE TABLE USERS (
ID INT PRIMARY KEY NOT NULL auto_increment,
FIRST_NAME VARCHAR(40) NOT NULL,
LAST_NAME VARCHAR(40) NOT NULL,
MAIL VARCHAR(40) NOT NULL
);


CREATE TABLE PLAYER(
ID INT PRIMARY KEY NOT NULL auto_increment,
PLAYER_NAME VARCHAR(40) NOT NULL,
BIRTH_DATE DATETIME NOT NULL,
TOTAL_CROWNS INT DEFAULT 0,
SPENT_CROWNS INT DEFAULT 0,
USER_ID INT,
foreign key (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE AVATAR(
ID INT PRIMARY KEY NOT NULL auto_increment,
AVATAR_NAME VARCHAR(40) NOT NULL,
URL VARCHAR(50),
´VALUE´ INT NOT NULL
);


CREATE TABLE UNLOCKED_AVATAR(
PLAYER_ID INT,
AVATAR_ID INT,
foreign key (PLAYER_ID) REFERENCES PLAYER(ID),
foreign key (AVATAR_ID) REFERENCES AVATAR(ID)
);

CREATE TABLE MODULE(
ID INT PRIMARY KEY NOT NULL auto_increment,
´DESCRIPTION´ VARCHAR(40) NOT NULL
);

CREATE TABLE APPLE(
ID INT PRIMARY KEY NOT NULL auto_increment,
´NAME´ VARCHAR(40) NOT NULL,
MODULE_ID INT,
foreign key (MODULE_ID) REFERENCES MODULE(ID)
);

CREATE TABLE EXERCISE_TYPE(
ID INT PRIMARY KEY NOT NULL auto_increment,
´DESCRIPTION´ VARCHAR(40) NOT NULL
);

CREATE TABLE EXERCISE(
ID INT PRIMARY KEY NOT NULL auto_increment,
´NAME´ VARCHAR(40) NOT NULL,
EXERCISE_TYPE_ID INT,
APPLE_ID INT,
PARAMETERS VARCHAR(300) NOT NULL,
foreign key (EXERCISE_TYPE_ID) REFERENCES EXERCISE_TYPE(ID),
foreign key (APPLE_ID) REFERENCES APPLE(ID)
);


CREATE TABLE RESULT(
PLAYER_ID INT,
APPLE_ID INT,
SCORE INT,
foreign key (PLAYER_ID) REFERENCES PLAYER(ID),
foreign key (APPLE_ID) REFERENCES APPLE(ID)
);










