CREATE DATABASE LECTI;
USE LECTI;

CREATE TABLE USUARIO (
ID INT PRIMARY KEY NOT NULL auto_increment,
NOMBRE VARCHAR(40) NOT NULL,
EMAIL  VARCHAR(40) NOT NULL,
DNI INT NOT NULL
);

CREATE TABLE JUGADOR(
ID INT PRIMARY KEY NOT NULL auto_increment,
NOMBRE VARCHAR(40) NOT NULL,
FECHA_NACIMIENTO DATETIME NOT NULL,
CORONAS_TOTALES INT DEFAULT 0,
CORONAS_GASTADAS INT DEFAULT 0,
ELO VARCHAR(15),
USUARIO_ID INT,
foreign key (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE AVATAR(
ID INT PRIMARY KEY NOT NULL auto_increment,
NOMBRE VARCHAR(40) NOT NULL,
URL VARCHAR(50),
VALOR INT NOT NULL
);


CREATE TABLE AVATAR_DESBLOQUEADO(
JUGADOR_ID INT,
AVATAR_ID INT,
foreign key (JUGADOR_ID) REFERENCES JUGADOR(ID),
foreign key (AVATAR_ID) REFERENCES AVATAR(ID)
);

CREATE TABLE MODULO(
ID INT PRIMARY KEY NOT NULL auto_increment,
DESCRIPCION VARCHAR(40) NOT NULL
);

CREATE TABLE MANZANA(
ID INT PRIMARY KEY NOT NULL auto_increment,
NOMBRE VARCHAR(40) NOT NULL,
MODULO_ID INT,
foreign key (MODULO_ID) REFERENCES MODULO(ID)
);

CREATE TABLE TIPO_EJERCICIO(
ID INT PRIMARY KEY NOT NULL auto_increment,
DESCRIPCION VARCHAR(40) NOT NULL
);

CREATE TABLE EJERCICIO(
ID INT PRIMARY KEY NOT NULL auto_increment,
NOMBRE VARCHAR(40) NOT NULL,
TIPO_EJERCICIO_ID INT,
MANZANA_ID INT,
PARAMETROS VARCHAR(300) NOT NULL,
foreign key (TIPO_EJERCICIO_ID) REFERENCES TIPO_EJERCICIO(ID),
foreign key (MANZANA_ID) REFERENCES MANZANA(ID)
);


CREATE TABLE RESULTADO(
JUGADOR_ID INT,
MANZANA_ID INT,
PUNTAJE INT,
foreign key (JUGADOR_ID) REFERENCES JUGADOR(ID),
foreign key (MANZANA_ID) REFERENCES MANZANA(ID)
);










